@startuml アクティビティ図

title 発券機アクティビティ

start
    :キー入力待ち;
switch (key?)
case (enter)
    :購入画面に移動;
    repeat
    :商品を選択する;
    repeat while (key is "c"?)
    :購入商品を表示する;
    :合計金額を表示する;
    :代金を入力する;
    :購入する;
    :おつりを返す;
    
case (esc)
    :管理画面に移動;
    :商品一覧を表示する;
    :総売上を表示する;
    :管理メニューを表示する;
    :管理コードを入力する;
    :商品の売り上げをリセットする;
case (q)
    :終了する;
endswitch
stop
@enduml
