@startuml ユースケース図
left to right direction
actor 利用者
actor 管理者

rectangle 食券機 {
利用者 --> (支払い金額入力)
利用者 --> (購入商品一覧)
利用者 --> (商品選択)
利用者 --> (商品情報閲覧)

管理者 --> (商品単価変更)
管理者 --> (販売個数・売上リセット)
管理者 --> (商品・販売個数・売上)
}
@enduml